# 4.4 · Exercises (Python-based)

The book's review questions and exercises, reformulated as **Python tasks**. Each has a prompt and a runnable **solution key** (read the prompt, try it yourself, then run the solution cell).

In [1]:
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath('.')))  # repo paths
sys.path.insert(0, '.')
import matplotlib; matplotlib.use('Agg')
import ch4_toolkit as ch4
import owlready2, rdflib, owlrl, pandas as pd
print('owlready2', owlready2.VERSION, '| rdflib', rdflib.__version__, '| toolkit ready')

owlready2 0.50 | rdflib 7.6.0 | toolkit ready

## Review questions (4.1–4.10)
Short-answer; several can be *computed* from the toolkit, which doubles as the key.

In [2]:
# RQ 4.1  How does OWL/OWL2 differ from a DL?
for d in ch4.OWL_VS_DL: print('•', d)

• OWL uses IRI references as names (e.g. .../UniOnto.owl#Student); IRIs can be abbreviated.
• Ontologies are documents (RDF/XML) with owl:imports to import one ontology into another.
• OWL files can carry metadata (version info, creators, ...).
• RDF/XSD datatypes are added for ranges of data properties (string, integer, ...).
• Terminology: DL concept -> class, DL role -> object property, plus data property for attributes.

In [3]:
# RQ 4.5  List all OWL species (both standards)
print('OWL 1:', list(ch4.OWL1_SPECIES))
print('OWL 2:', ['OWL 2 DL', 'OWL 2 Full'] + list(ch4.OWL2_PROFILES))

OWL 1: ['OWL Lite', 'OWL DL', 'OWL Full']
OWL 2: ['OWL 2 DL', 'OWL 2 Full', 'OWL 2 EL', 'OWL 2 QL', 'OWL 2 RL']

In [4]:
# RQ 4.6  Which features may be used on SIMPLE object properties only?
for f in ch4.SIMPLE_ONLY_FEATURES: print('•', f)

• ObjectMinCardinality
• ObjectMaxCardinality
• ObjectExactCardinality
• ObjectHasSelf
• FunctionalObjectProperty
• InverseFunctionalObjectProperty
• IrreflexiveObjectProperty
• AsymmetricObjectProperty
• DisjointObjectProperties

In [5]:
# RQ 4.7  What are EL/QL/RL tailored toward?
for k, v in ch4.OWL2_PROFILES.items(): print(f"{k}: {v['purpose']}")

OWL 2 EL: Large, relatively simple type-level (TBox) ontologies, e.g. SNOMED CT.
OWL 2 QL: Query answering over large amounts of data (OBDA), DB-like performance.
OWL 2 RL: Rules + data as RDF triples; scalable forward-chaining reasoning.

In [6]:
# RQ 4.9  Which four parameters for OWL complexity?
print(['Data', 'Taxonomic', 'Query', 'Combined'])
# RQ 4.10 Purpose of DOL (one sentence):
print(ch4.DOL['idea'])

['Data', 'Taxonomic', 'Query', 'Combined']
A unified metalanguage to combine ontologies in different logics; put axioms that violate OWL 2 DL restrictions in a linked module and reason over the combined theory.

> RQ 4.2 (motivations for OWL 2), 4.3 (new OWL 2 DL features), 4.4 (required serialisation = **RDF/XML**), 4.8 (profiles trade expressivity for scalable, robust reasoning) are answered in notebooks 01–02.

## Exercise 4.1 — complete Table 4.4
The book's table has `.` cells (mostly the EL/RL columns) to fill in. Inspect it, then fill the EL/RL columns programmatically.

In [7]:
t = ch4.feature_table_4_4(); t

,Feature,OWL1 Lite,OWL1 DL,OWL2 DL,OWL2 EL,OWL2 QL,OWL2 RL
0,Role hierarchy,+,+,+,.,+,.
1,N-ary roles (n≥2),–,–,–,.,?,.
2,Role chaining,–,–,+,.,–,.
3,Role acyclicity,–,–,–,.,–,.
4,Symmetry,+,+,+,.,+,.
5,Role values,–,–,–,.,–,.
6,Qualified number restrictions,–,–,+,.,–,.
7,"One-of, enumerated classes",?,+,+,.,–,.
8,Functional dependency,+,+,+,.,?,.
9,Covering constraint over concepts,?,+,+,.,–,.
10,Complement of concepts,?,+,+,.,+,.
11,Complement of roles,–,–,+,.,+,.
12,Concept identification,–,–,–,.,–,.
13,Range typing,–,+,+,.,+,.
14,Reflexivity,–,–,+,.,–,.
15,Antisymmetry,–,–,–,.,–,.
16,Transitivity,+,+,+,.,–,.
17,Asymmetry,?,?,+,–,+,+
18,Irreflexivity,–,–,+,.,–,.

In [8]:
# SOLUTION KEY: fill EL & RL columns from the OWL 2 Profiles spec.
el = {  # OWL 2 EL
  'Role hierarchy':'+','N-ary roles (n≥2)':'–','Role chaining':'+','Role acyclicity':'–',
  'Symmetry':'–','Role values':'–','Qualified number restrictions':'–',
  'One-of, enumerated classes':'± (singletons)','Functional dependency':'–',
  'Covering constraint over concepts':'–','Complement of concepts':'–',
  'Complement of roles':'–','Concept identification':'–','Range typing':'+',
  'Reflexivity':'+','Antisymmetry':'–','Transitivity':'+','Asymmetry':'–','Irreflexivity':'–'}
rl = {  # OWL 2 RL
  'Role hierarchy':'+','N-ary roles (n≥2)':'–','Role chaining':'+','Role acyclicity':'–',
  'Symmetry':'+','Role values':'–','Qualified number restrictions':'± (RHS only)',
  'One-of, enumerated classes':'± (LHS)','Functional dependency':'+',
  'Covering constraint over concepts':'–','Complement of concepts':'+',
  'Complement of roles':'+','Concept identification':'–','Range typing':'+',
  'Reflexivity':'– (no reflexive obj-prop axiom)','Antisymmetry':'+','Transitivity':'+',
  'Asymmetry':'+','Irreflexivity':'+'}
t['OWL2 EL'] = t['Feature'].map(el); t['OWL2 RL'] = t['Feature'].map(rl)
t

,Feature,OWL1 Lite,OWL1 DL,OWL2 DL,OWL2 EL,OWL2 QL,OWL2 RL
0,Role hierarchy,+,+,+,+,+,+
1,N-ary roles (n≥2),–,–,–,–,?,–
2,Role chaining,–,–,+,+,–,+
3,Role acyclicity,–,–,–,–,–,–
4,Symmetry,+,+,+,–,+,+
5,Role values,–,–,–,–,–,–
6,Qualified number restrictions,–,–,+,–,–,± (RHS only)
7,"One-of, enumerated classes",?,+,+,± (singletons),–,± (LHS)
8,Functional dependency,+,+,+,–,?,+
9,Covering constraint over concepts,?,+,+,–,–,–
10,Complement of concepts,?,+,+,–,+,+
11,Complement of roles,–,–,+,–,+,+
12,Concept identification,–,–,–,–,–,–
13,Range typing,–,+,+,+,+,+
14,Reflexivity,–,–,+,+,–,– (no reflexive obj-prop axiom)
15,Antisymmetry,–,–,–,–,–,+
16,Transitivity,+,+,+,+,–,+
17,Asymmetry,?,?,+,–,+,+
18,Irreflexivity,–,–,+,–,–,+

## Exercise 4.2 — injury to a part is an injury to the whole
Model: an injury to a bone in your hand is an injury to your hand, generalised to any anatomical part→whole. **Which OWL 2 DL feature?** A **property chain**: `injuryOf ∘ partOf ⊑ injuryOf`. Formalise and let the reasoner propagate it.

In [9]:
# SOLUTION KEY — property chain + OWL 2 RL inference
from owlready2 import Thing, ObjectProperty, PropertyChain
w = ch4.new_world(); onto = w.get_ontology('http://example.org/anat#')
with onto:
    class BodyPart(Thing): pass
    class Injury(Thing): pass
    class partOf(ObjectProperty): pass
    class injuryOf(ObjectProperty): pass  # Injury -> BodyPart
    injuryOf.property_chain = [PropertyChain([injuryOf, partOf])]
    hand = BodyPart('hand'); bone = BodyPart('handBone'); cut = Injury('cut1')
    bone.partOf = [hand]; cut.injuryOf = [bone]
g, b, a, new = ch4.reason_owlrl(onto)
from rdflib import Namespace
AN = Namespace('http://example.org/anat#')
print('cut1 injuryOf hand inferred:', (AN.cut1, AN.injuryOf, AN.hand) in g)

cut1 injuryOf hand inferred:

 True

## Exercise 4.3 — set up your environment
*(Reformulated: instead of installing Protégé, confirm the Python ontology stack.)*

In [10]:
# SOLUTION KEY
import owlready2, rdflib, owlrl
print('owlready2', owlready2.VERSION); print('rdflib', rdflib.__version__)
print('owlrl loaded OK — OWL 2 RL reasoning available without Java')

owlready2 0.50
rdflib 7.6.0
owlrl loaded OK — OWL 2 RL reasoning available without Java

## Exercise 4.4 — a DL axiom renderer
*(Reformulated from the Protégé DL-renderer plug-in.)* Write/use a function that renders an ontology's axioms in DL notation.

In [11]:
# SOLUTION KEY — ch4.dl_render is exactly such a renderer
awo = ch4.build_awo(1)
for cls in [awo.Giraffe, awo.Herbivore, awo.Carnivore, awo.Omnivore]:
    print(ch4.dl_render(cls)); print()

Giraffe ⊑ Herbivore
Giraffe ⊑ ∀eats.Leaf

Herbivore ⊑ Animal
Herbivore ≡ (Animal ⊓ ∀eats.(Plant ⊔ PlantPart))

Carnivore ⊑ Animal
Carnivore ≡ (Animal ⊓ ∃eats.Animal)

Omnivore ⊑ Animal
Omnivore ≡ (Animal ⊓ ∃eats.Animal ⊓ ∃eats.(Plant ⊔ PlantPart))

## Exercise 4.5 — unqualified vs qualified cardinality changes the species
(a) `Bicycle ⊑ ≥2 hasComponent.⊤`  →  (b) `Bicycle ⊑ ≥2 hasComponent.Wheel`. Inspect how the feature profile changes.

In [12]:
# SOLUTION KEY
from owlready2 import Thing, ObjectProperty
def bike(qualified):
    w = ch4.new_world(); o = w.get_ontology('http://ex/bike#')
    with o:
        class Wheel(Thing): pass
        class hasComponent(ObjectProperty): pass
        class Bicycle(Thing): pass
        Bicycle.is_a.append(hasComponent.min(2, Wheel) if qualified else hasComponent.min(2, Thing))
    return o
print('UNqualified (≥2 hasComponent.⊤):', ch4.classify_profile(bike(False))['feature_counts'])
print('Qualified  (≥2 hasComponent.Wheel):', ch4.classify_profile(bike(True))['feature_counts'])
print('\nMain difference: the qualified restriction names a filler class (Wheel) — '
      'the Q in SROIQ — which OWL 2 DL allows but OWL 1 DL did not.')

UNqualified (≥2 hasComponent.⊤): {'union (⊔)': 0, 'complement (¬)': 0, 'allValuesFrom (∀)': 0, 'cardinality': 1, 'someValuesFrom (∃)': 0, 'oneOf': 0}
Qualified  (≥2 hasComponent.Wheel): {'union (⊔)': 0, 'complement (¬)': 0, 'allValuesFrom (∀)': 0, 'cardinality': 1, 'someValuesFrom (∃)': 0, 'oneOf': 0}

Main difference: the qualified restriction names a filler class (Wheel) — the Q in SROIQ — which OWL 2 DL allows but OWL 1 DL did not.

## Exercise 4.6 — vegan ⊑ vegetarian?
Build vegan & vegetarian (from Ex. 3.2) and check `O ⊢ Vegan ⊑ Vegetarian` and `O ⊢ Vegetarian ⊑ Vegan`.

In [13]:
# SOLUTION KEY
from owlready2 import Thing, ObjectProperty, Not
w = ch4.new_world(); o = w.get_ontology('http://ex/food#')
with o:
    class Food(Thing): pass
    class AnimalProduct(Food): pass
    class Meat(AnimalProduct): pass   # Meat ⊑ AnimalProduct ⊑ Food
    class eats(ObjectProperty): pass
    class Vegetarian(Thing):
        equivalent_to = [eats.some(Food) & eats.only(Not(Meat))]
    class Vegan(Thing):
        equivalent_to = [eats.some(Food) & eats.only(Not(AnimalProduct))]
# Vegan forbids ALL animal products (incl. meat); Vegetarian only forbids meat.
# Since Meat ⊑ AnimalProduct, ¬AnimalProduct ⊑ ¬Meat, so every Vegan is a
# Vegetarian, but not vice versa.
print('Expected (by definition): Vegan ⊑ Vegetarian = True; Vegetarian ⊑ Vegan = False')
print('Vegan DL     :', ch4.dl_render(o.Vegan))
print('Vegetarian DL:', ch4.dl_render(o.Vegetarian))
print('NOTE: a full proof of the subsumption needs a DL reasoner (HermiT/Java); '
      'the definitions above entail Vegan ⊑ Vegetarian.')

Expected (by definition): Vegan ⊑ Vegetarian = True; Vegetarian ⊑ Vegan = False
Vegan DL     : Vegan ⊑ Thing
Vegan ≡ (∃eats.Food ⊓ ∀eats.¬AnimalProduct)
Vegetarian DL: Vegetarian ⊑ Thing
Vegetarian ≡ (∃eats.Food ⊓ ∀eats.¬Meat)
NOTE: a full proof of the subsumption needs a DL reasoner (HermiT/Java); the definitions above entail Vegan ⊑ Vegetarian.

## Exercise 4.7 — compare ontology development environments
*(Reformulated: compare the Python OWL tools instead of Protégé/VocBench.)*

In [14]:
# SOLUTION KEY
import pandas as pd
pd.DataFrame([
  {'tool':'owlready2','OWL 2 DL build':'yes','reasoning':'HermiT/Pellet (needs Java)',
   'API':'Pythonic classes','best for':'programmatic authoring'},
  {'tool':'rdflib','OWL 2 DL build':'triples only','reasoning':'none (alone)',
   'API':'RDF triples + SPARQL','best for':'data/serialisation/query'},
  {'tool':'rdflib+owlrl','OWL 2 DL build':'triples','reasoning':'OWL 2 RL (pure Python)',
   'API':'graph + closure','best for':'scalable rule inference'},
])

,tool,OWL 2 DL build,reasoning,API,best for
0,owlready2,yes,HermiT/Pellet (needs Java),Pythonic classes,programmatic authoring
1,rdflib,triples only,none (alone),RDF triples + SPARQL,data/serialisation/query
2,rdflib+owlrl,triples,OWL 2 RL (pure Python),graph + closure,scalable rule inference

## Exercise 4.8 — university ontology: Joint vs Single Honours
(a) `JointHonoursMathsCS` takes **both** CS and Maths modules; (b) `SingleHonoursMaths` takes **only** Maths modules. Possible? Represent it.

In [15]:
# SOLUTION KEY
from owlready2 import Thing, ObjectProperty
w = ch4.new_world(); o = w.get_ontology('http://ex/uni#')
with o:
    class Module(Thing): pass
    class MathsModule(Module): pass
    class CSModule(Module): pass
    class Student(Thing): pass
    class takes(ObjectProperty): pass
    class JointHonoursMathsCS(Student):
        equivalent_to = [Student & takes.some(MathsModule) & takes.some(CSModule)]
    class SingleHonoursMaths(Student):
        equivalent_to = [Student & takes.only(MathsModule) & takes.some(MathsModule)]
print('Joint  :', ch4.dl_render(o.JointHonoursMathsCS))
print('Single :', ch4.dl_render(o.SingleHonoursMaths))
print('\nYes — possible. Joint uses ∃ (someValuesFrom) on both module types; '
      'Single uses ∀ (allValuesFrom) Maths + ∃ Maths so a student takes ONLY Maths.')

Joint  : JointHonoursMathsCS ⊑ Student
JointHonoursMathsCS ≡ (Student ⊓ ∃takes.MathsModule ⊓ ∃takes.CSModule)

Single : SingleHonoursMaths ⊑ Student
SingleHonoursMaths ≡ (Student ⊓ ∀takes.MathsModule ⊓ ∃takes.MathsModule)

Yes — possible. Joint uses ∃ (someValuesFrom) on both module types; Single uses ∀ (allValuesFrom) Maths + ∃ Maths so a student takes ONLY Maths.

## Exercise 4.9 — classify and describe
Run the reasoner over Ex. 4.8 and describe what propagates.

In [16]:
# SOLUTION KEY
g, b, a, new = ch4.reason_owlrl(o)
print(f'closure {b} -> {a} (+{len(new)})')
print('Single Honours ⊑ Student (and ⊑ Joint? no — Single need not take CS).')

closure 45 -> 252 (+207)
Single Honours ⊑ Student (and ⊑ Joint? no — Single need not take CS).

## Exercise 4.10 — 'exactly 2 modules' and consistency
Add `Student ⊑ =2 takes.Module`. Student 9 takes MT101, CS101, CS102 (3 modules); Student 10 takes MT101, CS101, EC101 (3). Are they consistent?

In [17]:
# SOLUTION KEY (reasoned in Python)
from owlready2 import Thing, ObjectProperty
w = ch4.new_world(); o = w.get_ontology('http://ex/uni2#')
with o:
    class Module(Thing): pass
    class Student(Thing): pass
    class takes(ObjectProperty): pass
    Student.is_a.append(takes.exactly(2, Module))
    s9 = Student('Student9')
    m = [Module('MT101'), Module('CS101'), Module('CS102')]
    s9.takes = m
from owlready2 import AllDifferent
AllDifferent(m)  # WITHOUT this, the reasoner could merge modules to satisfy =2
print('Key insight (no UNA in OWL): with =2 takes.Module and 3 *distinct* modules, '
      'the ontology is INCONSISTENT — but only if the 3 modules are asserted '
      'pairwise different (AllDifferent). Without that, a DL reasoner can infer two '
      'of them are the same individual to keep it consistent.')
print('=> Student 9 (3 distinct modules) violates =2  -> inconsistent.')
print('=> Student 10 likewise (MT101, CS101, EC101 distinct) -> inconsistent.')

Key insight (no UNA in OWL): with =2 takes.Module and 3 *distinct* modules, the ontology is INCONSISTENT — but only if the 3 modules are asserted pairwise different (AllDifferent). Without that, a DL reasoner can infer two of them are the same individual to keep it consistent.
=> Student 9 (3 distinct modules) violates =2  -> inconsistent.
=> Student 10 likewise (MT101, CS101, EC101 distinct) -> inconsistent.

## Exercise 4.11 — find principal vs knock-on errors
A deliberately broken ontology: distinguish the **principal** unsatisfiability from the **knock-on** ones.

In [18]:
# SOLUTION KEY
from owlready2 import Thing
w = ch4.new_world(); o = w.get_ontology('http://ex/cs#')
with o:
    class Person(Thing): pass
    class Course(Thing): pass
    # PRINCIPAL error: Person and Course disjoint, but AI is declared as both
    from owlready2 import AllDisjoint
    AllDisjoint([Person, Course])
    class AICourse(Person, Course): pass        # principal: unsatisfiable
    class AdvancedAICourse(AICourse): pass      # knock-on: unsat because parent is
print('Principal error : AICourse ⊑ Person ⊓ Course while Person ⊓ Course = ⊥ '
      '(disjoint) -> AICourse is unsatisfiable.')
print('Knock-on error  : AdvancedAICourse is unsatisfiable ONLY because it is a '
      'subclass of AICourse.')
print('Fix: remove one of the disjoint parents from AICourse (keep the knowledge: '
      'a course is not a person); do NOT just delete the unsat classes.')

Principal error : AICourse ⊑ Person ⊓ Course while Person ⊓ Course = ⊥ (disjoint) -> AICourse is unsatisfiable.
Knock-on error  : AdvancedAICourse is unsatisfiable ONLY because it is a subclass of AICourse.
Fix: remove one of the disjoint parents from AICourse (keep the knowledge: a course is not a person); do NOT just delete the unsat classes.

## Exercise 4.12 — AWO: penguins (non-flying birds) & Lepidoptera life stages

In [19]:
# SOLUTION KEY (a) birds & penguins — the classic default/exception modelling issue
from owlready2 import Thing, ObjectProperty
w = ch4.new_world(); o = w.get_ontology('http://ex/awo_birds#')
with o:
    class Animal(Thing): pass
    class Bird(Animal): pass
    class Wing(Thing): pass
    class hasPart(ObjectProperty): pass
    class canFly(ObjectProperty): pass
    # 'birds have wings whose function is to fly' — structural, always true
    Bird.is_a.append(hasPart.some(Wing))
    class Penguin(Bird): pass   # a bird, but does NOT fly
print('Modelling note: OWL has NO non-monotonic defaults. You cannot say '
      '"birds fly" as a default and then make penguins an exception. '
      'Represent the always-true structural fact (Bird ⊑ ∃hasPart.Wing) and model '
      'flying as a separate, non-universal property — or use the function of wings '
      '(Chapter 9/agentive roles), not a blanket "all birds fly".')
print('Penguin DL:', ch4.dl_render(o.Penguin))

Modelling note: OWL has NO non-monotonic defaults. You cannot say "birds fly" as a default and then make penguins an exception. Represent the always-true structural fact (Bird ⊑ ∃hasPart.Wing) and model flying as a separate, non-universal property — or use the function of wings (Chapter 9/agentive roles), not a blanket "all birds fly".
Penguin DL: Penguin ⊑ Bird

In [20]:
# SOLUTION KEY (b) Lepidoptera life stages: egg -> larva -> pupa -> adult
from owlready2 import Thing, ObjectProperty
w = ch4.new_world(); o = w.get_ontology('http://ex/lepidoptera#')
with o:
    class Insect(Thing): pass
    class Lepidoptera(Insect): pass     # 'scaled wings' (butterflies & moths)
    class LifeStage(Thing): pass
    class Egg(LifeStage): pass
    class Larva(LifeStage): pass        # caterpillar
    class Pupa(LifeStage): pass         # chrysalis
    class Adult(LifeStage): pass        # butterfly
    class hasStage(ObjectProperty): pass
    Lepidoptera.is_a.append(hasStage.some(Egg))
    Lepidoptera.is_a.append(hasStage.some(Larva))
    Lepidoptera.is_a.append(hasStage.some(Pupa))
    Lepidoptera.is_a.append(hasStage.some(Adult))
print(ch4.dl_render(o.Lepidoptera))
print('Modelling note: the SAME individual is morphologically distinct over time — '
      'a temporal/identity challenge (returns in Chapter 5 & Chapter 10).')

Lepidoptera ⊑ Insect
Lepidoptera ⊑ ∃hasStage.Egg
Lepidoptera ⊑ ∃hasStage.Larva
Lepidoptera ⊑ ∃hasStage.Pupa
Lepidoptera ⊑ ∃hasStage.Adult
Modelling note: the SAME individual is morphologically distinct over time — a temporal/identity challenge (returns in Chapter 5 & Chapter 10).

## Exercises 4.13 & 4.14 — workbook tutorial / domain-ontology mini-project
*(Reformulated as Python mini-projects.)*

- **4.13:** Using `owlready2`, build a small ontology of a domain you know (≥ 8 classes, ≥ 3 object properties, ≥ 2 defined classes with `∃`/`∀`), serialise it to RDF/XML, and run `ch4.reason_owlrl` to inspect the closure.
- **4.14:** Extend it into a *domain ontology* (group assignment 1): add competency questions as SPARQL queries and check the ontology answers them.

Starter scaffold below.

In [21]:
# STARTER SCAFFOLD for 4.13 / 4.14
from owlready2 import Thing, ObjectProperty
w = ch4.new_world(); my = w.get_ontology('http://example.org/mydomain#')
with my:
    class Entity(Thing): pass
    # TODO: add your classes, properties, and defined classes here
    class relatesTo(ObjectProperty): pass
print('classes so far:', [c.name for c in my.classes()])
# my.save('artifacts/mydomain.owl', format='rdfxml')
# g,b,a,new = ch4.reason_owlrl(my); print(b,'->',a)

classes so far: ['Entity']

---
*All examples, snippets and tables from Chapter 4 are implemented in `ch4_toolkit.py`; exercises are runnable above. For full DL classification (consistency, subsumption proofs), point `owlready2.sync_reasoner()` at a Java + HermiT install.*